### ISSUE TITLE
DatabaseAssertionMode.NON_STRICT won't work if the expected data set includes its dtd file 

### ISSUE THREAD

**Issue by tmhung88** [springtestdbunit/spring-test-dbunit#65]
Let assume that the dtd file has all columns defined. And I included that dtd file inside my expected data set as I wanted auto-completion and validation. Suddenly, all of my test cases declared as NON_STRICT failed. When I debugged into the spring-test-dbunit source code, I found out the array ignoredColumns in the method NonStrictDatabaseAssertion.assertEquals was empty. Eventually, I removed the dtd inclusion, these just failed test cases worked again.

Is there a way to get expected data sets validated without giving up NON_STRICT mode?

**Comment by philwebb** [comment]
I'm not sure @mzagar might know.

**Comment by mzagar** [comment]
Hi all, I can confirm the described behavior and have written a [failing test](https://github.com/mzagar/spring-test-dbunit/commit/4af086917df858d2cd8d6e5f3fdb918ab0479f91) for it, but other than that I'm not really sure how to work around this isse.

When DTD is specified DbUnit uses it to generate expected table metadata and that metadata will always include all elements specified in DTD. This basically diasbles the NON_STRICT mode since that mode relies on the assumption dbunit metadata will not include columns which are not used - and that is not the case when DTD is used.

If you have any ideas how to approach this issue please do advise.

**Comment by mzagar** [comment]
Hi @tmhung88, @philwebb - I created a pull request with proposed solution to this issue, please let me know what you think: https://github.com/springtestdbunit/spring-test-dbunit/pull/71

Regards
