### ISSUE TITLE
Junit and @Before is run after @DatabaseSetup

### ISSUE THREAD

**Issue by sebglon** [springtestdbunit/spring-test-dbunit#73]
I need to init database structure before my test but @Before method is run after @DatabaseSetup
Is it possible to manage this order?

**Comment by philwebb** [comment]
It's not currently possible to change that order I'm afraid. You might be able to change `DbUnitTestExecutionListener` if you want a different order but I have a feeling that it might be tricky.

Perhaps we could modify `@DatabaseSetup` so that if it's used on a non `@Test` method it runs the method directly?
